{
 "title": "Solar Power Prediction | Different Methods",
 "time": { "from": "2025-01-06T18:30:00.000Z", "to": "2025-01-09T18:30:00.000Z" },
 "panels": [
  {
   "title": "Random Forest Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM random_forest_method LIMIT 10000 "
    }
   ]
  },
  {
   "title": "Linear Regression Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM linear_regression_method LIMIT 10000 "
    }
   ]
  },
  {
   "title": "Support Vector Regression",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * FROM svm_method LIMIT 5000 "
    }
   ]
  },
  {
   "title": "Random Forest Method - My Locality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * FROM rfm_locality LIMIT 5000 "
    }
   ]
  }
 ]
}